import "../styles/globals.css";
import Head from "next/head";
import { StrictMode } from "react";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>R3f</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ghost.png" />
      </Head>
      <StrictMode>
        <Component {...pageProps} />
      </StrictMode>
    </>
  );
}

export default MyApp;
